import { authTables } from "@convex-dev/auth/server";
import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

const roleEnum = v.union(
  v.literal("AD"),
  v.literal("NBD"),
  v.literal("AI-BOSS"),
  v.literal("COO"),
  v.literal("CFD"),
  v.literal("BUH"),
  v.literal("HOD"),
  v.literal("ADMIN"),
);

const paymentSplitValidator = v.object({
  splitNumber: v.number(),
  amountWithoutVat: v.number(),
  amountWithVat: v.optional(v.number()),
  vatRate: v.optional(v.number()),
  currencyRate: v.optional(v.number()),
  paidAt: v.number(),
  nextPaymentAt: v.optional(v.number()),
  remainingAmountWithoutVat: v.optional(v.number()),
  finplanCostIds: v.optional(v.array(v.string())),
  actorEmail: v.string(),
  actorName: v.optional(v.string()),
  createdAt: v.number(),
});

const plannedPaymentSplitValidator = v.object({
  splitNumber: v.number(),
  amountWithoutVat: v.number(),
  amountWithVat: v.optional(v.number()),
  vatRate: v.optional(v.number()),
  currencyRate: v.optional(v.number()),
  plannedAt: v.number(),
  finplanCostIds: v.optional(v.array(v.string())),
  actorEmail: v.string(),
  actorName: v.optional(v.string()),
  createdAt: v.number(),
});

const viewerAccessValidator = v.object({
  email: v.string(),
  fullName: v.optional(v.string()),
  grantedByEmail: v.string(),
  grantedByName: v.optional(v.string()),
  source: v.union(v.literal("share"), v.literal("mention")),
  grantedAt: v.number(),
});

const commentMentionValidator = v.object({
  key: v.optional(v.string()),
  email: v.string(),
  name: v.string(),
  token: v.optional(v.string()),
});

const schema = defineSchema({
  ...authTables,
  roles: defineTable({
    email: v.string(),
    roles: v.array(roleEnum),
    active: v.boolean(),
    isTest: v.boolean(),
    fullName: v.optional(v.string()),
    creatorTitle: v.optional(v.string()),
    hodDepartments: v.optional(v.array(v.string())),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_email", ["email"])
    .index("by_active", ["active"]),
  requests: defineTable({
    requestCode: v.optional(v.string()),
    title: v.optional(v.string()),
    createdBy: v.id("users"),
    createdByEmail: v.string(),
    createdByName: v.optional(v.string()),
    originalCreatedBy: v.optional(v.id("users")),
    originalCreatedByEmail: v.optional(v.string()),
    originalCreatedByName: v.optional(v.string()),
    archivedAuthorTransferredAt: v.optional(v.number()),
    archivedAt: v.optional(v.number()),
    requestArea: v.optional(v.string()),
    department: v.optional(v.string()),
    category: v.string(),
    businessCategory: v.optional(v.string()),
    amount: v.number(),
    amountWithVat: v.optional(v.number()),
    vatRate: v.optional(v.number()),
    currency: v.string(),
    fundingSource: v.string(),
    counterparty: v.optional(v.string()),
    paymentMethod: v.optional(v.string()),
    cfdTag: v.optional(v.string()),
    contractLink: v.optional(v.string()),
    contractAttachmentCount: v.optional(v.number()),
    lastContractAttachmentName: v.optional(v.string()),
    dueDiligenceChecked: v.optional(v.boolean()),
    dueDiligenceJiraLink: v.optional(v.string()),
    prepaymentRequired: v.optional(v.boolean()),
    prepaymentAmount: v.optional(v.number()),
    prepaymentAmountWithVat: v.optional(v.number()),
    prepaymentDate: v.optional(v.number()),
    justification: v.string(),
    details: v.optional(v.string()),
    investmentReturn: v.optional(v.string()),
    clientName: v.string(),
    contacts: v.array(v.string()),
    relatedRequests: v.optional(v.array(v.string())),
    links: v.array(v.string()),
    attachmentCount: v.optional(v.number()),
    lastAttachmentName: v.optional(v.string()),
    financePlanLinks: v.optional(v.array(v.string())),
    incomingAmount: v.optional(v.number()),
    incomingAmountWithVat: v.optional(v.number()),
    incomingRatio: v.optional(v.number()),
    shipmentDate: v.optional(v.number()),
    shipmentMonth: v.optional(v.string()),
    viewerAccess: v.optional(v.array(viewerAccessValidator)),
    requiredHodDepartments: v.optional(v.array(v.string())),
    specialists: v.optional(
      v.array(
        v.object({
          id: v.string(),
          name: v.string(),
          sourceType: v.optional(v.string()),
          contractorTypes: v.optional(v.array(v.string())),
          department: v.optional(v.string()),
          hours: v.optional(v.number()),
          directCost: v.optional(v.number()),
          taxAmount: v.optional(v.number()),
          taxUnknown: v.optional(v.boolean()),
          amountIncludesTaxes: v.optional(v.boolean()),
          amountExcludesTaxes: v.optional(v.boolean()),
          hodConfirmed: v.optional(v.boolean()),
          buhConfirmed: v.optional(v.boolean()),
          validationSkipped: v.optional(v.boolean()),
        }),
      ),
    ),
    requiredRoles: v.array(roleEnum),
    status: v.union(
      v.literal("draft"),
      v.literal("hod_pending"),
      v.literal("pending"),
      v.literal("approved"),
      v.literal("rejected"),
      v.literal("awaiting_payment"),
      v.literal("payment_planned"),
      v.literal("partially_paid"),
      v.literal("paid"),
      v.literal("closed"),
    ),
    previousClosedStatus: v.optional(
      v.union(v.literal("approved"), v.literal("paid")),
    ),
    isCanceled: v.optional(v.boolean()),
    canceledAt: v.optional(v.number()),
    approvalDeadline: v.optional(v.number()),
    neededBy: v.optional(v.number()),
    paidBy: v.optional(v.number()),
    awaitingPaymentAt: v.optional(v.number()),
    awaitingPaymentByEmail: v.optional(v.string()),
    awaitingPaymentByName: v.optional(v.string()),
    paidAt: v.optional(v.number()),
    paidByEmail: v.optional(v.string()),
    paidByName: v.optional(v.string()),
    actualPaidAmount: v.optional(v.number()),
    actualPaidAmountWithVat: v.optional(v.number()),
    paymentResidualAmount: v.optional(v.number()),
    paymentResidualAmountWithVat: v.optional(v.number()),
    plannedPaymentAmount: v.optional(v.number()),
    plannedPaymentAmountWithVat: v.optional(v.number()),
    paymentCurrencyRate: v.optional(v.number()),
    paymentPlannedAt: v.optional(v.number()),
    paymentPlannedByEmail: v.optional(v.string()),
    paymentPlannedByName: v.optional(v.string()),
    finplanCostIds: v.optional(v.array(v.string())),
    paymentSplits: v.optional(v.array(paymentSplitValidator)),
    plannedPaymentSplits: v.optional(v.array(plannedPaymentSplitValidator)),
    approvalReminderSentAt: v.optional(v.number()),
    paymentReminderSentAt: v.optional(v.number()),
    closeReminderSentAt: v.optional(v.number()),
    submittedAt: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_createdBy", ["createdBy"])
    .index("by_createdByEmail", ["createdByEmail"])
    .index("by_status", ["status"]),
  approvals: defineTable({
    requestId: v.id("requests"),
    role: roleEnum,
    department: v.optional(v.string()),
    status: v.union(
      v.literal("pending"),
      v.literal("approved"),
      v.literal("rejected"),
    ),
    comment: v.optional(v.string()),
    decidedAt: v.optional(v.number()),
    reviewerId: v.optional(v.id("users")),
    reviewerEmail: v.optional(v.string()),
    requestedByRole: v.optional(roleEnum),
    requestedByEmail: v.optional(v.string()),
    requestedByName: v.optional(v.string()),
    requestedAt: v.optional(v.number()),
    requestedByApprovalId: v.optional(v.id("approvals")),
    requestedByDeferred: v.optional(v.boolean()),
  })
    .index("by_request", ["requestId"])
    .index("by_role", ["role"])
    .index("by_status", ["status"]),
  comments: defineTable({
    requestId: v.id("requests"),
    authorId: v.id("users"),
    authorEmail: v.string(),
    authorName: v.optional(v.string()),
    body: v.string(),
    mentions: v.optional(v.array(commentMentionValidator)),
    parentId: v.optional(v.id("comments")),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_request", ["requestId"])
    .index("by_parent", ["parentId"]),
  requestAttachments: defineTable({
    requestId: v.id("requests"),
    storageId: v.id("_storage"),
    fileName: v.string(),
    fileSize: v.optional(v.number()),
    contentType: v.optional(v.string()),
    attachmentType: v.optional(v.union(v.literal("general"), v.literal("contract"))),
    uploadedByEmail: v.string(),
    uploadedByName: v.optional(v.string()),
    createdAt: v.number(),
  }).index("by_request", ["requestId"]),
  requestChangeLogs: defineTable({
    requestId: v.id("requests"),
    groupId: v.optional(v.string()),
    field: v.string(),
    fromValue: v.optional(v.string()),
    toValue: v.optional(v.string()),
    authorEmail: v.string(),
    authorName: v.optional(v.string()),
    triggeredRepeatApproval: v.optional(v.boolean()),
    groupSummary: v.optional(v.string()),
    createdAt: v.number(),
  }).index("by_request", ["requestId"]),
  requestTimelineEvents: defineTable({
    requestId: v.id("requests"),
    type: v.string(),
    title: v.string(),
    description: v.optional(v.string()),
    actorEmail: v.optional(v.string()),
    actorName: v.optional(v.string()),
    metadata: v.optional(v.string()),
    createdAt: v.number(),
  }).index("by_request", ["requestId"]),
  requestEmailLogs: defineTable({
    requestId: v.optional(v.id("requests")),
    emailType: v.string(),
    recipients: v.array(v.string()),
    subject: v.string(),
    status: v.union(v.literal("sent"), v.literal("failed")),
    error: v.optional(v.string()),
    createdAt: v.number(),
  }).index("by_request", ["requestId"]),
  presalesQuotas: defineTable({
    monthKey: v.string(),
    year: v.number(),
    month: v.number(),
    quota: v.number(),
    quotaWithVat: v.optional(v.number()),
    adjustedQuota: v.optional(v.number()),
    adjustedQuotaWithVat: v.optional(v.number()),
    vatRate: v.optional(v.number()),
    spent: v.number(),
    spentWithVat: v.optional(v.number()),
    updatedAt: v.number(),
  }).index("by_monthKey", ["monthKey"]),
  aiToolQuotas: defineTable({
    monthKey: v.string(),
    year: v.number(),
    month: v.number(),
    quota: v.number(),
    quotaWithVat: v.optional(v.number()),
    adjustedQuota: v.optional(v.number()),
    adjustedQuotaWithVat: v.optional(v.number()),
    vatRate: v.optional(v.number()),
    spent: v.number(),
    spentWithVat: v.optional(v.number()),
    updatedAt: v.number(),
  }).index("by_monthKey", ["monthKey"]),
  cfdTags: defineTable({
    name: v.string(),
    requestArea: v.optional(v.string()),
    department: v.optional(v.string()),
    active: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_name", ["name"])
    .index("by_area_department", ["requestArea", "department"]),
  requestBusinessCategories: defineTable({
    name: v.string(),
    active: v.boolean(),
    sortOrder: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_name", ["name"]),
  administrationQuotas: defineTable({
    monthKey: v.string(),
    departmentKey: v.string(),
    departmentName: v.optional(v.string()),
    tagName: v.optional(v.string()),
    year: v.number(),
    month: v.number(),
    quota: v.number(),
    quotaWithVat: v.optional(v.number()),
    adjustedQuota: v.optional(v.number()),
    adjustedQuotaWithVat: v.optional(v.number()),
    vatRate: v.optional(v.number()),
    manualSpent: v.optional(v.number()),
    manualSpentWithVat: v.optional(v.number()),
    spent: v.number(),
    spentWithVat: v.optional(v.number()),
    updatedAt: v.number(),
  })
    .index("by_monthKey", ["monthKey"])
    .index("by_month_department", ["monthKey", "departmentKey"])
    .index("by_month_department_tag", ["monthKey", "departmentKey", "tagName"]),
  quotaChangeLogs: defineTable({
    monthKey: v.string(),
    changeType: v.optional(v.union(v.literal("quota"), v.literal("manual_spent"))),
    level: v.union(v.literal("total"), v.literal("department"), v.literal("tag")),
    departmentKey: v.optional(v.string()),
    tagName: v.optional(v.string()),
    fromQuota: v.optional(v.number()),
    toQuota: v.number(),
    fromManualSpent: v.optional(v.number()),
    toManualSpent: v.optional(v.number()),
    fromManualSpentWithVat: v.optional(v.number()),
    toManualSpentWithVat: v.optional(v.number()),
    actorEmail: v.string(),
    actorName: v.optional(v.string()),
    requestId: v.optional(v.id("requests")),
    createdAt: v.number(),
  })
    .index("by_monthKey", ["monthKey"])
    .index("by_request", ["requestId"]),
  cfdQuotas: defineTable({
    monthKey: v.string(),
    year: v.number(),
    month: v.number(),
    quota: v.number(),
    quotaWithVat: v.optional(v.number()),
    adjustedQuota: v.optional(v.number()),
    adjustedQuotaWithVat: v.optional(v.number()),
    vatRate: v.optional(v.number()),
    spent: v.number(),
    spentWithVat: v.optional(v.number()),
    updatedAt: v.number(),
  }).index("by_monthKey", ["monthKey"]),
  cooQuotas: defineTable({
    monthKey: v.string(),
    year: v.number(),
    month: v.number(),
    quota: v.number(),
    quotaWithVat: v.optional(v.number()),
    adjustedQuota: v.optional(v.number()),
    adjustedQuotaWithVat: v.optional(v.number()),
    vatRate: v.optional(v.number()),
    spent: v.number(),
    spentWithVat: v.optional(v.number()),
    updatedAt: v.number(),
  }).index("by_monthKey", ["monthKey"]),
  requestCounters: defineTable({
    key: v.string(),
    nextNumber: v.number(),
    updatedAt: v.number(),
  }).index("by_key", ["key"]),
});

export default schema;
